HOSTS:
  ubuntu-1604-x64:
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get update && apt-get install -y locales net-tools wget && locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
